version: '3'
services:
  web:
    image: daviscontainer
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: davis
        awslogs-region: us-west-2
        awslogs-stream-prefix: web
