//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class contactMessages:public drogon::DrTemplate<contactMessages>
{
public:
	contactMessages(){};
	virtual ~contactMessages(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
