//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "contactOnly.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string contactOnly::genText(const DrTemplateData& contactOnly_view_data)
{
	drogon::OStringStream contactOnly_tmp_stream;
	std::string layoutName{""};
	contactOnly_tmp_stream << "<!DOCTYPE html>\n";
	contactOnly_tmp_stream << "<!--\n";
	contactOnly_tmp_stream << "    Licensed to the Apache Software Foundation (ASF) under one\n";
	contactOnly_tmp_stream << "    or more contributor license agreements.  See the NOTICE file\n";
	contactOnly_tmp_stream << "    distributed with this work for additional information\n";
	contactOnly_tmp_stream << "    regarding copyright ownership.  The ASF licenses this file\n";
	contactOnly_tmp_stream << "    to you under the Apache License, Version 2.0 (the\n";
	contactOnly_tmp_stream << "    \"License\"); you may not use this file except in compliance\n";
	contactOnly_tmp_stream << "    with the License.  You may obtain a copy of the License at\n";
contactOnly_tmp_stream<<"\n";
	contactOnly_tmp_stream << "    http://www.apache.org/licenses/LICENSE-2.0\n";
contactOnly_tmp_stream<<"\n";
	contactOnly_tmp_stream << "    Unless required by applicable law or agreed to in writing,\n";
	contactOnly_tmp_stream << "    software distributed under the License is distributed on an\n";
	contactOnly_tmp_stream << "    \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY\n";
	contactOnly_tmp_stream << "     KIND, either express or implied.  See the License for the\n";
	contactOnly_tmp_stream << "    specific language governing permissions and limitations\n";
	contactOnly_tmp_stream << "    under the License.\n";
	contactOnly_tmp_stream << "-->\n";
	contactOnly_tmp_stream << "<html>\n";
	contactOnly_tmp_stream << "   <head>\n";
	contactOnly_tmp_stream << "      <meta charset=\"utf-8\" />\n";
	contactOnly_tmp_stream << "      <!--\n";
	contactOnly_tmp_stream << "        Customize this policy to fit your own app's needs. For more guidance, see:\n";
	contactOnly_tmp_stream << "            https://github.com/apache/cordova-plugin-whitelist/blob/master/README.md#content-security-policy\n";
	contactOnly_tmp_stream << "        Some notes:\n";
	contactOnly_tmp_stream << "            * gap: is required only on iOS (when using UIWebView) and is needed for JS->native communication\n";
	contactOnly_tmp_stream << "            * https://ssl.gstatic.com is required only on Android and is needed for TalkBack to function properly\n";
	contactOnly_tmp_stream << "            * Disables use of inline scripts in order to mitigate risk of XSS vulnerabilities. To change this:\n";
	contactOnly_tmp_stream << "                * Enable inline JS: add 'unsafe-inline' to default-src\n";
	contactOnly_tmp_stream << "        -->\n";
	contactOnly_tmp_stream << "      <meta\n";
	contactOnly_tmp_stream << "         http-equiv=\"Content-Security-Policy\"\n";
	contactOnly_tmp_stream << "         content=\"default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;\"\n";
	contactOnly_tmp_stream << "      />\n";
	contactOnly_tmp_stream << "      <meta name=\"format-detection\" content=\"telephone=no\" />\n";
	contactOnly_tmp_stream << "      <meta name=\"msapplication-tap-highlight\" content=\"no\" />\n";
	contactOnly_tmp_stream << "      <meta name=\"viewport\" content=\"initial-scale=1, width=device-width, viewport-fit=cover\" />\n";
	contactOnly_tmp_stream << "      <meta name=\"color-scheme\" content=\"light dark\" />\n";
	contactOnly_tmp_stream << "      <title>Davis | Chat</title>\n";
	contactOnly_tmp_stream << "      <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" />\n";
	contactOnly_tmp_stream << "      <link rel=\"stylesheet\" href=\"css/contact.min.css\" />\n";
	contactOnly_tmp_stream << "   </head>\n";
	contactOnly_tmp_stream << "   <body>\n";
	contactOnly_tmp_stream << "      <!--Navigation Bar-->\n";
	contactOnly_tmp_stream << "      <nav class=\"navbar navbar-dark nav-colour fixed-top\">\n";
	contactOnly_tmp_stream << "         <div class=\"container-fluid\">\n";
	contactOnly_tmp_stream << "            <span class=\"navbar-brand mb-0 h1\">Davis</span>\n";
	contactOnly_tmp_stream << "            <span class=\"navbar-brand mb-0 h1\">Contacts</span>\n";
	contactOnly_tmp_stream << "            <div class=\"dropdown\">\n";
	contactOnly_tmp_stream << "               <button\n";
	contactOnly_tmp_stream << "                  class=\"btn btn-secondary transparent\"\n";
	contactOnly_tmp_stream << "                  type=\"button\"\n";
	contactOnly_tmp_stream << "                  id=\"dropdownMenuButton2\"\n";
	contactOnly_tmp_stream << "                  data-bs-toggle=\"dropdown\"\n";
	contactOnly_tmp_stream << "                  aria-expanded=\"false\"\n";
	contactOnly_tmp_stream << "               >\n";
	contactOnly_tmp_stream << "                  <img class=\"icon dropdown-icon\" src=\"images/menu.svg\" alt=\"Send\" />\n";
	contactOnly_tmp_stream << "               </button>\n";
	contactOnly_tmp_stream << "               <ul\n";
	contactOnly_tmp_stream << "                  class=\"dropdown-menu dropdown-menu-dark dropdown-menu-right\"\n";
	contactOnly_tmp_stream << "                  aria-labelledby=\"dropdownMenuButton2\"\n";
	contactOnly_tmp_stream << "               >\n";
	contactOnly_tmp_stream << "                  <li><a class=\"dropdown-item\" href=\"#\">Add contact</a></li>\n";
	contactOnly_tmp_stream << "                  <li><a class=\"dropdown-item\" href=\"#\">Send message</a></li>\n";
	contactOnly_tmp_stream << "                  <li><hr class=\"dropdown-divider\" /></li>\n";
	contactOnly_tmp_stream << "                  <li><a class=\"dropdown-item\" href=\"#\">Log out</a></li>\n";
	contactOnly_tmp_stream << "               </ul>\n";
	contactOnly_tmp_stream << "            </div>\n";
	contactOnly_tmp_stream << "         </div>\n";
	contactOnly_tmp_stream << "      </nav>\n";
	contactOnly_tmp_stream << "      <div class=\"container-fluid contact-container\">\n";
	contactOnly_tmp_stream << "         <div class=\"row contact-row\">\n";
	contactOnly_tmp_stream << "            <div class=\"col-3 contact-left\">\n";
	contactOnly_tmp_stream << "               <img src=\"images/demos/men/man1.jpg\" alt=\"\" />\n";
	contactOnly_tmp_stream << "            </div>\n";
	contactOnly_tmp_stream << "            <div class=\"col-9 contact-right\">\n";
	contactOnly_tmp_stream << "               <a href=\"messages.html\">\n";
	contactOnly_tmp_stream << "                  <div class=\"contact-name\">Mike Johnson</div>\n";
	contactOnly_tmp_stream << "                  <div class=\"contact-message\">Hiya mate, just seeing how that meeting went...</div>\n";
	contactOnly_tmp_stream << "               </a>\n";
	contactOnly_tmp_stream << "            </div>\n";
	contactOnly_tmp_stream << "         </div>\n";
	contactOnly_tmp_stream << "         <div class=\"row contact-row\">\n";
	contactOnly_tmp_stream << "            <div class=\"col-3 contact-left\">\n";
	contactOnly_tmp_stream << "               <img src=\"images/demos/women/woman1.jpg\" alt=\"\" />\n";
	contactOnly_tmp_stream << "            </div>\n";
	contactOnly_tmp_stream << "            <div class=\"col-9 contact-right\">\n";
	contactOnly_tmp_stream << "               <a href=\"messages.html\">\n";
	contactOnly_tmp_stream << "                  <div class=\"contact-name\">Ava Leday</div>\n";
	contactOnly_tmp_stream << "                  <div class=\"contact-message\">Did you get the package I sent the other day?</div>\n";
	contactOnly_tmp_stream << "               </a>\n";
	contactOnly_tmp_stream << "            </div>\n";
	contactOnly_tmp_stream << "         </div>\n";
	contactOnly_tmp_stream << "         <div class=\"row contact-row\">\n";
	contactOnly_tmp_stream << "            <div class=\"col-3 contact-left\">\n";
	contactOnly_tmp_stream << "               <img src=\"images/demos/men/man2.jpg\" alt=\"\" />\n";
	contactOnly_tmp_stream << "            </div>\n";
	contactOnly_tmp_stream << "            <div class=\"col-9 contact-right\">\n";
	contactOnly_tmp_stream << "               <a href=\"messages.html\">\n";
	contactOnly_tmp_stream << "                  <div class=\"contact-name\">Tom McAllister</div>\n";
	contactOnly_tmp_stream << "                  <div class=\"contact-message\">Go to the discord vc, big news!!!</div>\n";
	contactOnly_tmp_stream << "               </a>\n";
	contactOnly_tmp_stream << "            </div>\n";
	contactOnly_tmp_stream << "         </div>\n";
	contactOnly_tmp_stream << "         <div class=\"row contact-row\">\n";
	contactOnly_tmp_stream << "            <div class=\"col-3 contact-left\">\n";
	contactOnly_tmp_stream << "               <img src=\"images/demos/women/woman2.jpg\" alt=\"\" />\n";
	contactOnly_tmp_stream << "            </div>\n";
	contactOnly_tmp_stream << "            <div class=\"col-9 contact-right\">\n";
	contactOnly_tmp_stream << "               <a href=\"messages.html\">\n";
	contactOnly_tmp_stream << "                  <div class=\"contact-name\">Tracey Amar</div>\n";
	contactOnly_tmp_stream << "                  <div class=\"contact-message\">\n";
	contactOnly_tmp_stream << "                     Make sure you get the work done before Thursday\n";
	contactOnly_tmp_stream << "                  </div></a\n";
	contactOnly_tmp_stream << "               >\n";
	contactOnly_tmp_stream << "            </div>\n";
	contactOnly_tmp_stream << "         </div>\n";
	contactOnly_tmp_stream << "         <div class=\"row contact-row\">\n";
	contactOnly_tmp_stream << "            <div class=\"col-3 contact-left\">\n";
	contactOnly_tmp_stream << "               <img src=\"images/demos/men/man3.jpg\" alt=\"\" />\n";
	contactOnly_tmp_stream << "            </div>\n";
	contactOnly_tmp_stream << "            <div class=\"col-9 contact-right\">\n";
	contactOnly_tmp_stream << "               <a href=\"messages.html\">\n";
	contactOnly_tmp_stream << "                  <div class=\"contact-name\">Bruce Oneal</div>\n";
	contactOnly_tmp_stream << "                  <div class=\"contact-message\">Go to the discord vc, big news!!!</div></a\n";
	contactOnly_tmp_stream << "               >\n";
	contactOnly_tmp_stream << "            </div>\n";
	contactOnly_tmp_stream << "         </div>\n";
	contactOnly_tmp_stream << "         <div class=\"row contact-row\">\n";
	contactOnly_tmp_stream << "            <div class=\"col-3 contact-left\">\n";
	contactOnly_tmp_stream << "               <img src=\"images/demos/women/woman3.jpg\" alt=\"\" />\n";
	contactOnly_tmp_stream << "            </div>\n";
	contactOnly_tmp_stream << "            <div class=\"col-9 contact-right\">\n";
	contactOnly_tmp_stream << "               <a href=\"messages.html\">\n";
	contactOnly_tmp_stream << "                  <div class=\"contact-name\">Vanessa Clark</div>\n";
	contactOnly_tmp_stream << "                  <div class=\"contact-message\">\n";
	contactOnly_tmp_stream << "                     Make sure you get the work done before Thursday\n";
	contactOnly_tmp_stream << "                  </div></a\n";
	contactOnly_tmp_stream << "               >\n";
	contactOnly_tmp_stream << "            </div>\n";
	contactOnly_tmp_stream << "         </div>\n";
	contactOnly_tmp_stream << "         <div class=\"row contact-row\">\n";
	contactOnly_tmp_stream << "            <div class=\"col-3 contact-left\">\n";
	contactOnly_tmp_stream << "               <img src=\"images/demos/men/man4.jpg\" alt=\"\" />\n";
	contactOnly_tmp_stream << "            </div>\n";
	contactOnly_tmp_stream << "            <div class=\"col-9 contact-right\">\n";
	contactOnly_tmp_stream << "               <a href=\"messages.html\">\n";
	contactOnly_tmp_stream << "                  <div class=\"contact-name\">Jon Wells</div>\n";
	contactOnly_tmp_stream << "                  <div class=\"contact-message\">Go to the discord vc, big news!!!</div></a\n";
	contactOnly_tmp_stream << "               >\n";
	contactOnly_tmp_stream << "            </div>\n";
	contactOnly_tmp_stream << "         </div>\n";
	contactOnly_tmp_stream << "         <div class=\"row contact-row\">\n";
	contactOnly_tmp_stream << "            <div class=\"col-3 contact-left\">\n";
	contactOnly_tmp_stream << "               <img src=\"images/demos/women/woman4.jpg\" alt=\"\" />\n";
	contactOnly_tmp_stream << "            </div>\n";
	contactOnly_tmp_stream << "            <div class=\"col-9 contact-right\">\n";
	contactOnly_tmp_stream << "               <a href=\"messages.html\">\n";
	contactOnly_tmp_stream << "                  <div class=\"contact-name\">Jessica Miles</div>\n";
	contactOnly_tmp_stream << "                  <div class=\"contact-message\">\n";
	contactOnly_tmp_stream << "                     Make sure you get the work done before Thursday\n";
	contactOnly_tmp_stream << "                  </div></a\n";
	contactOnly_tmp_stream << "               >\n";
	contactOnly_tmp_stream << "            </div>\n";
	contactOnly_tmp_stream << "         </div>\n";
	contactOnly_tmp_stream << "      </div>\n";
	contactOnly_tmp_stream << "      <script src=\"js/bootstrap.min.js\"></script>\n";
	contactOnly_tmp_stream << "   </body>\n";
	contactOnly_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(contactOnly_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = contactOnly_view_data;
auto str = std::move(contactOnly_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
