//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class messages:public drogon::DrTemplate<messages>
{
public:
	messages(){};
	virtual ~messages(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
