//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class profile:public drogon::DrTemplate<profile>
{
public:
	profile(){};
	virtual ~profile(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
