//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class contactOnly:public drogon::DrTemplate<contactOnly>
{
public:
	contactOnly(){};
	virtual ~contactOnly(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
