//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "login.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string login::genText(const DrTemplateData& login_view_data)
{
	drogon::OStringStream login_tmp_stream;
	std::string layoutName{""};
	login_tmp_stream << "<!DOCTYPE html>\n";
	login_tmp_stream << "<html lang=\"en\" dir=\"ltr\">\n";
	login_tmp_stream << "  <head>\n";
	login_tmp_stream << "    <meta charset=\"utf-8\">\n";
	login_tmp_stream << "    <meta name=\"viewport\" content=\"initial-scale=1, width=device-width, viewport-fit=cover\" />\n";
	login_tmp_stream << "    <title>Login</title>\n";
	login_tmp_stream << "    <link rel=\"stylesheet\" href=\"css/login.css\">\n";
	login_tmp_stream << "    <script src=\"login.js\" defer></script>\n";
login_tmp_stream<<"\n";
	login_tmp_stream << "</head>\n";
login_tmp_stream<<"\n";
	login_tmp_stream << "<body>\n";
login_tmp_stream<<"\n";
	login_tmp_stream << "    <form action=\"/login\" method=\"post\">\n";
	login_tmp_stream << "  <div class=\"loginbox\">\n";
login_tmp_stream<<"\n";
	login_tmp_stream << "    <h1>Login</h1>\n";
login_tmp_stream<<"\n";
login_tmp_stream<<"\n";
	login_tmp_stream << "    <p>Username</p>\n";
	login_tmp_stream << "    <input type=\"text\" class='inputBox' placeholder=\"Enter Username\" name=\"userName\" required><br>\n";
login_tmp_stream<<"\n";
	login_tmp_stream << "    <p>Password</p>\n";
	login_tmp_stream << "    <input type=\"password\" placeholder=\"Enter Password\" name=\"password\" required><br>\n";
login_tmp_stream<<"\n";
login_tmp_stream<<"\n";
	login_tmp_stream << "  <button type=\"submit\" name=\"Login\">Login</button>\n";
login_tmp_stream<<"\n";
	login_tmp_stream << "  <a href=\"#\">Forgot Your Password</a><br>\n";
login_tmp_stream<<"\n";
	login_tmp_stream << "  <a href=\"signup.html\">Signup</a>\n";
	login_tmp_stream << "  </div>\n";
login_tmp_stream<<"\n";
	login_tmp_stream << "</form>\n";
login_tmp_stream<<"\n";
login_tmp_stream<<"\n";
	login_tmp_stream << "  </body>\n";
	login_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(login_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = login_view_data;
auto str = std::move(login_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
