//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "messages.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string messages::genText(const DrTemplateData& messages_view_data)
{
	drogon::OStringStream messages_tmp_stream;
	std::string layoutName{""};
	messages_tmp_stream << "<!DOCTYPE html>\n";
	messages_tmp_stream << "<!--\n";
	messages_tmp_stream << "    Licensed to the Apache Software Foundation (ASF) under one\n";
	messages_tmp_stream << "    or more contributor license agreements.  See the NOTICE file\n";
	messages_tmp_stream << "    distributed with this work for additional information\n";
	messages_tmp_stream << "    regarding copyright ownership.  The ASF licenses this file\n";
	messages_tmp_stream << "    to you under the Apache License, Version 2.0 (the\n";
	messages_tmp_stream << "    \"License\"); you may not use this file except in compliance\n";
	messages_tmp_stream << "    with the License.  You may obtain a copy of the License at\n";
messages_tmp_stream<<"\n";
	messages_tmp_stream << "    http://www.apache.org/licenses/LICENSE-2.0\n";
messages_tmp_stream<<"\n";
	messages_tmp_stream << "    Unless required by applicable law or agreed to in writing,\n";
	messages_tmp_stream << "    software distributed under the License is distributed on an\n";
	messages_tmp_stream << "    \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY\n";
	messages_tmp_stream << "     KIND, either express or implied.  See the License for the\n";
	messages_tmp_stream << "    specific language governing permissions and limitations\n";
	messages_tmp_stream << "    under the License.\n";
	messages_tmp_stream << "-->\n";
	messages_tmp_stream << "<html>\n";
	messages_tmp_stream << "   <head>\n";
	messages_tmp_stream << "      <meta charset=\"utf-8\" />\n";
	messages_tmp_stream << "      <!--\n";
	messages_tmp_stream << "        Customize this policy to fit your own app's needs. For more guidance, see:\n";
	messages_tmp_stream << "            https://github.com/apache/cordova-plugin-whitelist/blob/master/README.md#content-security-policy\n";
	messages_tmp_stream << "        Some notes:\n";
	messages_tmp_stream << "            * gap: is required only on iOS (when using UIWebView) and is needed for JS->native communication\n";
	messages_tmp_stream << "            * https://ssl.gstatic.com is required only on Android and is needed for TalkBack to function properly\n";
	messages_tmp_stream << "            * Disables use of inline scripts in order to mitigate risk of XSS vulnerabilities. To change this:\n";
	messages_tmp_stream << "                * Enable inline JS: add 'unsafe-inline' to default-src\n";
	messages_tmp_stream << "        -->\n";
	messages_tmp_stream << "      <meta\n";
	messages_tmp_stream << "         http-equiv=\"Content-Security-Policy\"\n";
	messages_tmp_stream << "         content=\"default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;\"\n";
	messages_tmp_stream << "      />\n";
	messages_tmp_stream << "      <meta name=\"format-detection\" content=\"telephone=no\" />\n";
	messages_tmp_stream << "      <meta name=\"msapplication-tap-highlight\" content=\"no\" />\n";
	messages_tmp_stream << "      <meta name=\"viewport\" content=\"initial-scale=1, width=device-width, viewport-fit=cover\" />\n";
	messages_tmp_stream << "      <meta name=\"color-scheme\" content=\"light dark\" />\n";
	messages_tmp_stream << "      <title>Davis | Chat</title>\n";
	messages_tmp_stream << "      <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" />\n";
	messages_tmp_stream << "      <link rel=\"stylesheet\" href=\"css/messages.min.css\" />\n";
	messages_tmp_stream << "   </head>\n";
	messages_tmp_stream << "   <body>\n";
	messages_tmp_stream << "         <nav class=\"navbar navbar-expand-lg navbar-dark nav-colour\">\n";
	messages_tmp_stream << "            <div class=\"container-fluid\">\n";
	messages_tmp_stream << "               <span class=\"navbar-brand mb-0 h1\"><a id=\"back\" href=\"contactMessages.html\"><-</a></span>\n";
	messages_tmp_stream << "               <span class=\"navbar-brand mb-0 h1\" id=\"header-contact-name\"></span>\n";
	messages_tmp_stream << "               <div class=\"dropdown\">\n";
	messages_tmp_stream << "                  <button\n";
	messages_tmp_stream << "                     class=\"btn btn-secondary transparent\"\n";
	messages_tmp_stream << "                     type=\"button\"\n";
	messages_tmp_stream << "                     id=\"dropdownMenuButton2\"\n";
	messages_tmp_stream << "                     data-bs-toggle=\"dropdown\"\n";
	messages_tmp_stream << "                     aria-expanded=\"false\"\n";
	messages_tmp_stream << "                  >\n";
	messages_tmp_stream << "                     <img class=\"icon dropdown-icon\" src=\"images/menu.svg\" alt=\"Send\" />\n";
	messages_tmp_stream << "                  </button>\n";
	messages_tmp_stream << "                  <ul\n";
	messages_tmp_stream << "                     class=\"dropdown-menu dropdown-menu-dark dropdown-menu-right\"\n";
	messages_tmp_stream << "                     aria-labelledby=\"dropdownMenuButton2\"\n";
	messages_tmp_stream << "                  >\n";
	messages_tmp_stream << "                     <li><a class=\"dropdown-item\" href=\"#\">View contact info</a></li>\n";
	messages_tmp_stream << "                     <li><hr class=\"dropdown-divider\" /></li>\n";
	messages_tmp_stream << "                     <li><a class=\"dropdown-item\" href=\"#\">Send location</a></li>\n";
	messages_tmp_stream << "                     <li><a class=\"dropdown-item\" href=\"#\">Send SOS</a></li>\n";
	messages_tmp_stream << "                     <li><a class=\"dropdown-item\" href=\"#\">Send prayers</a></li>\n";
	messages_tmp_stream << "                  </ul>\n";
	messages_tmp_stream << "               </div>\n";
	messages_tmp_stream << "            </div>\n";
	messages_tmp_stream << "         </nav>\n";
	messages_tmp_stream << "         \n";
	messages_tmp_stream << "         <div class=\"error-field\" id=\"error-field\"></div>\n";
	messages_tmp_stream << "         <div class=\"chat container-fluid\" id=\"chat\">\n";
messages_tmp_stream<<"\n";
	messages_tmp_stream << "            <div class=\"error\" id=\"error-box\">\n";
	messages_tmp_stream << "               <span class=\"close-button\" id=\"error-close\">&#10005</span>\n";
	messages_tmp_stream << "            </div>\n";
	messages_tmp_stream << "            <div class=\"row no-gutters\">\n";
	messages_tmp_stream << "               <div class=\"col\">\n";
	messages_tmp_stream << "                  <div class=\"message\">\n";
	messages_tmp_stream << "                     <div class=\"message-left-first\">Hi</div>\n";
	messages_tmp_stream << "                  </div>\n";
	messages_tmp_stream << "               </div>\n";
	messages_tmp_stream << "            </div>\n";
	messages_tmp_stream << "            <div class=\"row no-gutters\">\n";
	messages_tmp_stream << "               <div class=\"col\">\n";
	messages_tmp_stream << "                  <div class=\"message\">\n";
	messages_tmp_stream << "                     <div class=\"message-left\">How are you doing?</div>\n";
	messages_tmp_stream << "                     <div class=\"message-time-left\">11:32am</div>\n";
	messages_tmp_stream << "                  </div>\n";
	messages_tmp_stream << "               </div>\n";
	messages_tmp_stream << "            </div>\n";
	messages_tmp_stream << "            <div class=\"row no-gutters\">\n";
	messages_tmp_stream << "               <div class=\"col\">\n";
	messages_tmp_stream << "                  <div class=\"message\">\n";
	messages_tmp_stream << "                     <div class=\"message-right-first float-end\">I'm good :)</div>\n";
	messages_tmp_stream << "                  </div>\n";
	messages_tmp_stream << "               </div>\n";
	messages_tmp_stream << "            </div>\n";
	messages_tmp_stream << "            <div class=\"row no-gutters\">\n";
	messages_tmp_stream << "               <div class=\"col\">\n";
	messages_tmp_stream << "                  <div class=\"message\">\n";
	messages_tmp_stream << "                     <div class=\"message-right float-end\">How about you?</div>\n";
	messages_tmp_stream << "                     <div class=\"message-time-right float-end\">11:49am</div>\n";
	messages_tmp_stream << "                  </div>\n";
	messages_tmp_stream << "               </div>\n";
	messages_tmp_stream << "            </div>\n";
	messages_tmp_stream << "            <div class=\"row no-gutters\">\n";
	messages_tmp_stream << "               <div class=\"col\">\n";
	messages_tmp_stream << "                  <div class=\"message\">\n";
	messages_tmp_stream << "                     <div class=\"message-left-first\">\n";
	messages_tmp_stream << "                        Long message example. Lorem ipsum dolor sit amet consectetur adipisicing elit.\n";
	messages_tmp_stream << "                        Quis, veniam non. Deserunt rerum cum laudantium itaque voluptates sint, saepe\n";
	messages_tmp_stream << "                        et.\n";
	messages_tmp_stream << "                     </div>\n";
	messages_tmp_stream << "                     <div class=\"message-time-left\">1:12pm</div>\n";
	messages_tmp_stream << "                  </div>\n";
	messages_tmp_stream << "               </div>\n";
	messages_tmp_stream << "            </div>\n";
	messages_tmp_stream << "            <div class=\"row no-gutters\">\n";
	messages_tmp_stream << "               <div class=\"col\">\n";
	messages_tmp_stream << "                  <div class=\"message\">\n";
	messages_tmp_stream << "                     <div class=\"message-right-first float-end\">\n";
	messages_tmp_stream << "                        Even longer message example. Lorem ipsum dolor sit amet consectetur adipisicing\n";
	messages_tmp_stream << "                        elit. Dolores dolorum numquam aperiam amet corrupti id, officiis error\n";
	messages_tmp_stream << "                        consectetur consequatur iure unde quisquam voluptatem soluta voluptas excepturi\n";
	messages_tmp_stream << "                        esse mollitia voluptatibus iste temporibus ipsa exercitationem modi debitis\n";
	messages_tmp_stream << "                        animi ab! Itaque, rerum eum. Quisquam tempore quasi harum sint aperiam. Nostrum\n";
	messages_tmp_stream << "                        omnis iure vitae. et.\n";
	messages_tmp_stream << "                     </div>\n";
	messages_tmp_stream << "                     <div class=\"message-time-right float-end\">1:12pm</div>\n";
	messages_tmp_stream << "                  </div>\n";
	messages_tmp_stream << "               </div>\n";
	messages_tmp_stream << "            </div>\n";
	messages_tmp_stream << "         </div>\n";
	messages_tmp_stream << "         <footer class=\"footer\">\n";
	messages_tmp_stream << "            <div class=\"container-fluid\">\n";
	messages_tmp_stream << "               <div class=\"row\">\n";
	messages_tmp_stream << "                  <div class=\"col-12 no-margin\">\n";
	messages_tmp_stream << "                     <div class=\"message-row\">\n";
	messages_tmp_stream << "                        <input\n";
	messages_tmp_stream << "                           type=\"text\"\n";
	messages_tmp_stream << "                           class=\"form-control\"\n";
	messages_tmp_stream << "                           name=\"message-input\"\n";
	messages_tmp_stream << "                           id=\"message-input\"\n";
	messages_tmp_stream << "                           placeholder=\"Your message here...\"\n";
	messages_tmp_stream << "                        />\n";
	messages_tmp_stream << "                        <button\n";
	messages_tmp_stream << "                           type=\"submit\"\n";
	messages_tmp_stream << "                           class=\"btn btn-primary submit-button transparent\"\n";
	messages_tmp_stream << "                           id=\"submit\"\n";
	messages_tmp_stream << "                        >\n";
	messages_tmp_stream << "                           <img class=\"icon\" src=\"images/send.svg\" alt=\"Send\" />\n";
	messages_tmp_stream << "                        </button>\n";
	messages_tmp_stream << "                     </div>\n";
	messages_tmp_stream << "                  </div>\n";
	messages_tmp_stream << "               </div>\n";
	messages_tmp_stream << "            </div>\n";
	messages_tmp_stream << "         </footer>\n";
	messages_tmp_stream << "      <script src=\"js/bootstrap.min.js\"></script>\n";
	messages_tmp_stream << "      <script src=\"js/validator.min.js\"></script>\n";
	messages_tmp_stream << "      <script src=\"js/time.min.js\"></script>\n";
	messages_tmp_stream << "      <script src=\"js/messages.js\"></script>\n";
	messages_tmp_stream << "   </body>\n";
	messages_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(messages_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = messages_view_data;
auto str = std::move(messages_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
